apiVersion: v1
kind: ConfigMap
metadata:
  name: test-backend-post-config
data:
  application-dev.yml: |
    spring:
      datasource:
        url: jdbc:mysql://k8s-external-post-mysql-service:3306/post?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        username: user
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        open-in-view: false
