apiVersion: v1
kind: Service
metadata:
  name: k8s-external-post-mysql-service
spec:
  selector:
    app: post-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP