apiVersion: v1
kind: Service
metadata:
  name: test-backend-post-service
spec:
  selector:
    app: test-backend-post
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP